### ISSUE TITLE
Standardisation

### ISSUE THREAD

**Issue by x1704e** [ingbrzy/MA-XML-7.0-PORTUGUESE#7]
Hello! 

I would like to suggest that we compile a list of standardised translations, because I've encountered a few terms that have been translated differently in different places. I've also encountered some non-standard capitalisation, such as "Modo de Uma mão", where I think it would be better to have "Mão" capitalised as well or type "uma" using a lowercase u. I have opted for the latter, personally.

These are the suggestions for standard translations I would like to make thus far:

Standard Translation | Non-Standard Translations
------------ | -------------
Conta Mi (standalone), conta Mi (in a sentence) | Conta MI
Lista de bloqueios (standalone), lista de bloqueios (in a sentence) | Lista de Bloqueios
Lista de excepções (standalone), lista de excepções (in a sentence) | Lista de Excepções
Loja de Temas MIUI  | not any of the other two or three variations I encountered
MiKey | Mi key
Modo de uma mão (standalone), modo de uma mão (in a sentence)  | Modo de Uma mão
Modo de voo (standalone), modo de voo (in a sentence) | Modo Voo, modo de Voo, modo de avião etc.
multimédia | multimídia
Nuvem Mi  | Núvem Mi
palavra-passe | palavra passe
Pré-visualização | Previsualização
Telemóvel (when referring to the device itself) | Telefone, Telefone celular

Which other terms do you all think should be included in this list for us and for future volunteers?

**Comment by lemaran** [comment]
Hi, may I sugest a change?
"Senha" in place of "palavra passe".
" Nuvem" is without acute accent só it's right.
Do you need translation of toggles terms? Or do you already have them?
Sorry for any mistake but I dont have experience in software translating.
But any terms you ask opinion in portuguese (brazilian) translating, I will
gladly help.

Thanks for your good work
Em 22/04/2015 23:44, "x1704e" <notifications@github.com> escreveu:

**Comment by x1704e** [comment]
Hi. Thanks for your offer to help out! I'm sure that you know that there are different preferences for some words over others in Portugal and Brazil, and "palavra-passe" is one of them. If you would like to assist in translating MIUI to Brazilian Portuguese, I am sure that there is a way to do so, but I don't think that it's done here (I am new around here, so I'm not entirely sure). Have a good day!

**Comment by lemaran** [comment]
Thats fine by me. Majority of terms are the same so I could help. Palavra
passe is better than password so thats fine.
Best regards
Em 22/04/2015 23:44, "x1704e" <notifications@github.com> escreveu:

**Comment by Edufex** [comment]
Como voçês sabem não é facil fazer todo este trabalho sozinho  e por essa razão acredito que tenha erros mas está melhor  do que não haver nenhuma tradução.
Ao contrario de muita gente eu não tenho muito tempo disponivel para estar sempre a verificar erros e como tal tenho familia e vida própria e toda a ajuda será bem vinda de modo a melhorar-mos a tradução desde que não tenhamos os chamados brasileirismos ( Voçê,Tela,celular,Senha...)

Now in english:

As you know it's not easy to do all this work alone and for this reason I believe it has errors but it is better than to be no translation.
Unlike many people I do not have much time available to be kept up to check for errors and as such have family and life and all help will be appreciated in order to improve them to me the translation since we do not have the so-called brazilianisms

**Comment by nunytes** [comment]
You're the man! :)

I already tried to learn how to translate this things, but I found it a way hard without HTML or so knowledge. But with your hard work (I really appreciate that!), finally I was able to translate my phone that already have a miui 6 port, but Portuguese, only have Brazilian.. Now it's working great, after making changes with your hard work. It's not everything changed, but more than 90% is (despite some stock things and custom things introduced by the author in English and some Chinese characters). 

keep the good work! 
Cheers :)
